dist: focal
matrix:
  include:
    - language: go
      go:
        - master
    - language: minimal
      services:
        - docker
      script:
        - set -o errexit;
          docker run --rm -i ghcr.io/hadolint/hadolint < docker/Dockerfile;
          shellcheck --enable=all docker/entrypoint.sh;
          docker build -t packer-builder-arm -f docker/Dockerfile .;
          docker run --rm --privileged -v /dev:/dev -v ${PWD}:/build packer-builder-arm build boards/raspberry-pi/archlinuxarm.json -extra-system-packages=bmap-tools,zstd;
          du -h raspberry-pi.img;
          du -h --apparent-size raspberry-pi.img
