/* Note:  This file was autogenerated by Database/JsonToIPC.py */
/*        See Database/Readme.txt for details. */
/*        If you are hand-modifying this file, keep in mind that */
/*        your work will be lost if you run JsonToIPC.py again. */

#include "AcTypeConverter.h"


void StringToAcType(const char* Msg, size_t MsgLen, struct AcType *AC)
{

      long Isc,i;
      char line[512] = "Blank";
      long RequestTimeRefresh = 0;
      long Done;
      long Imsg,Iline;
      double DbleVal[30];
      long LongVal[30];

      long Year,doy,Hour,Minute;
      double Second;
      long Month,Day;
      if (MsgLen <= 0) return; /* Bail out if no message */

       Done = 0;
      Imsg = 0;
      while(!Done) {
         /* Parse lines from Msg, newline-delimited */
         Iline = 0;
         memset(line,'\0',512);
         while((Msg[Imsg] != '\n') && (Iline < 511) && (Imsg < MsgLen)) {
            line[Iline++] = Msg[Imsg++];
         }
         line[Iline++] = Msg[Imsg++];
         if (AC->EchoEnabled) printf("%s",line);

         if (sscanf(line,"TIME %ld-%ld-%ld:%ld:%lf\n",
            &Year,&doy,&Hour,&Minute,&Second) == 5) {
            RequestTimeRefresh = 1;
         }

         if (sscanf(line,"SC[%ld].AC.DynTime = %le",
            &Isc,
            &DbleVal[0]) == 2) {
            if (Isc == AC->ID) {
               AC->DynTime = DbleVal[0];
            }
         }

         if (sscanf(line,"SC[%ld].AC.DT = %le",
            &Isc,
            &DbleVal[0]) == 2) {
            if (Isc == AC->ID) {
               AC->DT = DbleVal[0];
            }
         }

         if (sscanf(line,"SC[%ld].AC.Time = %le",
            &Isc,
            &DbleVal[0]) == 2) {
            if (Isc == AC->ID) {
               AC->Time = DbleVal[0];
            }
         }

         if (sscanf(line,"SC[%ld].AC.wbn = %le %le %le",
            &Isc,
            &DbleVal[0],
            &DbleVal[1],
            &DbleVal[2]) == 4) {
            if (Isc == AC->ID) {
               AC->wbn[0] = DbleVal[0];
               AC->wbn[1] = DbleVal[1];
               AC->wbn[2] = DbleVal[2];
            }
         }

         if (sscanf(line,"SC[%ld].AC.qbn = %le %le %le %le",
            &Isc,
            &DbleVal[0],
            &DbleVal[1],
            &DbleVal[2],
            &DbleVal[3]) == 5) {
            if (Isc == AC->ID) {
               AC->qbn[0] = DbleVal[0];
               AC->qbn[1] = DbleVal[1];
               AC->qbn[2] = DbleVal[2];
               AC->qbn[3] = DbleVal[3];
            }
         }

         if (sscanf(line,"SC[%ld].AC.svn = %le %le %le",
            &Isc,
            &DbleVal[0],
            &DbleVal[1],
            &DbleVal[2]) == 4) {
            if (Isc == AC->ID) {
               AC->svn[0] = DbleVal[0];
               AC->svn[1] = DbleVal[1];
               AC->svn[2] = DbleVal[2];
            }
         }

         if (sscanf(line,"SC[%ld].AC.bvn = %le %le %le",
            &Isc,
            &DbleVal[0],
            &DbleVal[1],
            &DbleVal[2]) == 4) {
            if (Isc == AC->ID) {
               AC->bvn[0] = DbleVal[0];
               AC->bvn[1] = DbleVal[1];
               AC->bvn[2] = DbleVal[2];
            }
         }


         if (sscanf(line,"SC[%ld].AC.PosN = %le %le %le",
            &Isc,
            &DbleVal[0],
            &DbleVal[1],
            &DbleVal[2]) == 4) {
            if (Isc == AC->ID) {
               AC->PosN[0] = DbleVal[0];
               AC->PosN[1] = DbleVal[1];
               AC->PosN[2] = DbleVal[2];
            }
         }

         if (sscanf(line,"SC[%ld].AC.VelN = %le %le %le",
            &Isc,
            &DbleVal[0],
            &DbleVal[1],
            &DbleVal[2]) == 4) {
            if (Isc == AC->ID) {
               AC->VelN[0] = DbleVal[0];
               AC->VelN[1] = DbleVal[1];
               AC->VelN[2] = DbleVal[2];
            }
         }

         if (sscanf(line,"SC[%ld].AC.G[%ld].Ang = %le %le %le",
            &Isc,&i,
            &DbleVal[0],
            &DbleVal[1],
            &DbleVal[2]) == 5) {
            if (Isc == AC->ID) {
               if (AC->G != NULL) {
                  AC->G[i].Ang[0] = DbleVal[0];
                  AC->G[i].Ang[1] = DbleVal[1];
                  AC->G[i].Ang[2] = DbleVal[2];
               }
            }
         }

         if (sscanf(line,"SC[%ld].AC.Gyro[%ld].Rate = %le",
            &Isc,&i,
            &DbleVal[0]) == 3) {
            if (Isc == AC->ID) {
               if (AC->Gyro != NULL) {
                  AC->Gyro[i].Rate = DbleVal[0];
               }
            }
         }

         if (sscanf(line,"SC[%ld].AC.MAG[%ld].Field = %le",
            &Isc,&i,
            &DbleVal[0]) == 3) {
            if (Isc == AC->ID) {
               if (AC->MAG != NULL) {
                  AC->MAG[i].Field = DbleVal[0];
               }
            }
         }

         if (sscanf(line,"SC[%ld].AC.CSS[%ld].Valid = %ld",
            &Isc,&i,
            &LongVal[0]) == 3) {
            if (Isc == AC->ID) {
               if (AC->CSS != NULL) {
                  AC->CSS[i].Valid = LongVal[0];
               }
            }
         }

         if (sscanf(line,"SC[%ld].AC.CSS[%ld].Illum = %le",
            &Isc,&i,
            &DbleVal[0]) == 3) {
            if (Isc == AC->ID) {
               if (AC->CSS != NULL) {
                  AC->CSS[i].Illum = DbleVal[0];
               }
            }
         }

         if (sscanf(line,"SC[%ld].AC.FSS[%ld].Valid = %ld",
            &Isc,&i,
            &LongVal[0]) == 3) {
            if (Isc == AC->ID) {
               if (AC->FSS != NULL) {
                  AC->FSS[i].Valid = LongVal[0];
               }
            }
         }

         if (sscanf(line,"SC[%ld].AC.FSS[%ld].SunAng = %le %le",
            &Isc,&i,
            &DbleVal[0],
            &DbleVal[1]) == 4) {
            if (Isc == AC->ID) {
               if (AC->FSS != NULL) {
                  AC->FSS[i].SunAng[0] = DbleVal[0];
                  AC->FSS[i].SunAng[1] = DbleVal[1];
               }
            }
         }

         if (sscanf(line,"SC[%ld].AC.FSS[%ld].SunVecS = %le %le %le",
            &Isc,&i,
            &DbleVal[0],
            &DbleVal[1],
            &DbleVal[2]) == 5) {
            if (Isc == AC->ID) {
               if (AC->FSS != NULL) {
                  AC->FSS[i].SunVecS[0] = DbleVal[0];
                  AC->FSS[i].SunVecS[1] = DbleVal[1];
                  AC->FSS[i].SunVecS[2] = DbleVal[2];
               }
            }
         }

         if (sscanf(line,"SC[%ld].AC.FSS[%ld].SunVecB = %le %le %le",
            &Isc,&i,
            &DbleVal[0],
            &DbleVal[1],
            &DbleVal[2]) == 5) {
            if (Isc == AC->ID) {
               if (AC->FSS != NULL) {
                  AC->FSS[i].SunVecB[0] = DbleVal[0];
                  AC->FSS[i].SunVecB[1] = DbleVal[1];
                  AC->FSS[i].SunVecB[2] = DbleVal[2];
               }
            }
         }

         if (sscanf(line,"SC[%ld].AC.ST[%ld].Valid = %ld",
            &Isc,&i,
            &LongVal[0]) == 3) {
            if (Isc == AC->ID) {
               if (AC->ST != NULL) {
                  AC->ST[i].Valid = LongVal[0];
               }
            }
         }

         if (sscanf(line,"SC[%ld].AC.ST[%ld].qn = %le %le %le %le",
            &Isc,&i,
            &DbleVal[0],
            &DbleVal[1],
            &DbleVal[2],
            &DbleVal[3]) == 6) {
            if (Isc == AC->ID) {
               if (AC->ST != NULL) {
                  AC->ST[i].qn[0] = DbleVal[0];
                  AC->ST[i].qn[1] = DbleVal[1];
                  AC->ST[i].qn[2] = DbleVal[2];
                  AC->ST[i].qn[3] = DbleVal[3];
               }
            }
         }

         if (sscanf(line,"SC[%ld].AC.ST[%ld].qbn = %le %le %le %le",
            &Isc,&i,
            &DbleVal[0],
            &DbleVal[1],
            &DbleVal[2],
            &DbleVal[3]) == 6) {
            if (Isc == AC->ID) {
               if (AC->ST != NULL) {
                  AC->ST[i].qbn[0] = DbleVal[0];
                  AC->ST[i].qbn[1] = DbleVal[1];
                  AC->ST[i].qbn[2] = DbleVal[2];
                  AC->ST[i].qbn[3] = DbleVal[3];
               }
            }
         }

         if (sscanf(line,"SC[%ld].AC.GPS[%ld].Valid = %ld",
            &Isc,&i,
            &LongVal[0]) == 3) {
            if (Isc == AC->ID) {
               if (AC->GPS != NULL) {
                  AC->GPS[i].Valid = LongVal[0];
               }
            }
         }

         if (sscanf(line,"SC[%ld].AC.GPS[%ld].Rollover = %ld",
            &Isc,&i,
            &LongVal[0]) == 3) {
            if (Isc == AC->ID) {
               if (AC->GPS != NULL) {
                  AC->GPS[i].Rollover = LongVal[0];
               }
            }
         }

         if (sscanf(line,"SC[%ld].AC.GPS[%ld].Week = %ld",
            &Isc,&i,
            &LongVal[0]) == 3) {
            if (Isc == AC->ID) {
               if (AC->GPS != NULL) {
                  AC->GPS[i].Week = LongVal[0];
               }
            }
         }

         if (sscanf(line,"SC[%ld].AC.GPS[%ld].Sec = %le",
            &Isc,&i,
            &DbleVal[0]) == 3) {
            if (Isc == AC->ID) {
               if (AC->GPS != NULL) {
                  AC->GPS[i].Sec = DbleVal[0];
               }
            }
         }

         if (sscanf(line,"SC[%ld].AC.GPS[%ld].PosN = %le %le %le",
            &Isc,&i,
            &DbleVal[0],
            &DbleVal[1],
            &DbleVal[2]) == 5) {
            if (Isc == AC->ID) {
               if (AC->GPS != NULL) {
                  AC->GPS[i].PosN[0] = DbleVal[0];
                  AC->GPS[i].PosN[1] = DbleVal[1];
                  AC->GPS[i].PosN[2] = DbleVal[2];
               }
            }
         }

         if (sscanf(line,"SC[%ld].AC.GPS[%ld].VelN = %le %le %le",
            &Isc,&i,
            &DbleVal[0],
            &DbleVal[1],
            &DbleVal[2]) == 5) {
            if (Isc == AC->ID) {
               if (AC->GPS != NULL) {
                  AC->GPS[i].VelN[0] = DbleVal[0];
                  AC->GPS[i].VelN[1] = DbleVal[1];
                  AC->GPS[i].VelN[2] = DbleVal[2];
               }
            }
         }

         if (sscanf(line,"SC[%ld].AC.GPS[%ld].PosW = %le %le %le",
            &Isc,&i,
            &DbleVal[0],
            &DbleVal[1],
            &DbleVal[2]) == 5) {
            if (Isc == AC->ID) {
               if (AC->GPS != NULL) {
                  AC->GPS[i].PosW[0] = DbleVal[0];
                  AC->GPS[i].PosW[1] = DbleVal[1];
                  AC->GPS[i].PosW[2] = DbleVal[2];
               }
            }
         }

         if (sscanf(line,"SC[%ld].AC.GPS[%ld].VelW = %le %le %le",
            &Isc,&i,
            &DbleVal[0],
            &DbleVal[1],
            &DbleVal[2]) == 5) {
            if (Isc == AC->ID) {
               if (AC->GPS != NULL) {
                  AC->GPS[i].VelW[0] = DbleVal[0];
                  AC->GPS[i].VelW[1] = DbleVal[1];
                  AC->GPS[i].VelW[2] = DbleVal[2];
               }
            }
         }

         if (sscanf(line,"SC[%ld].AC.GPS[%ld].Lng = %le",
            &Isc,&i,
            &DbleVal[0]) == 3) {
            if (Isc == AC->ID) {
               if (AC->GPS != NULL) {
                  AC->GPS[i].Lng = DbleVal[0];
               }
            }
         }

         if (sscanf(line,"SC[%ld].AC.GPS[%ld].Lat = %le",
            &Isc,&i,
            &DbleVal[0]) == 3) {
            if (Isc == AC->ID) {
               if (AC->GPS != NULL) {
                  AC->GPS[i].Lat = DbleVal[0];
               }
            }
         }

         if (sscanf(line,"SC[%ld].AC.GPS[%ld].Alt = %le",
            &Isc,&i,
            &DbleVal[0]) == 3) {
            if (Isc == AC->ID) {
               if (AC->GPS != NULL) {
                  AC->GPS[i].Alt = DbleVal[0];
               }
            }
         }

         if (sscanf(line,"SC[%ld].AC.GPS[%ld].WgsLng = %le",
            &Isc,&i,
            &DbleVal[0]) == 3) {
            if (Isc == AC->ID) {
               if (AC->GPS != NULL) {
                  AC->GPS[i].WgsLng = DbleVal[0];
               }
            }
         }

         if (sscanf(line,"SC[%ld].AC.GPS[%ld].WgsLat = %le",
            &Isc,&i,
            &DbleVal[0]) == 3) {
            if (Isc == AC->ID) {
               if (AC->GPS != NULL) {
                  AC->GPS[i].WgsLat = DbleVal[0];
               }
            }
         }

         if (sscanf(line,"SC[%ld].AC.GPS[%ld].WgsAlt = %le",
            &Isc,&i,
            &DbleVal[0]) == 3) {
            if (Isc == AC->ID) {
               if (AC->GPS != NULL) {
                  AC->GPS[i].WgsAlt = DbleVal[0];
               }
            }
         }

         if (sscanf(line,"SC[%ld].AC.Accel[%ld].Acc = %le",
            &Isc,&i,
            &DbleVal[0]) == 3) {
            if (Isc == AC->ID) {
               if (AC->Accel != NULL) {
                  AC->Accel[i].Acc = DbleVal[0];
               }
            }
         }

         if (sscanf(line,"SC[%ld].AC.EPS[%ld].Wheel_I = %le",
            &Isc,&i,
            &DbleVal[0]) == 3) {
            if (Isc == AC->ID) {
               if (AC->EPS != NULL) {
                  AC->EPS[i].Wheel_I = DbleVal[0];
               }
            }
         }

         if (sscanf(line,"SC[%ld].AC.EPS[%ld].IMU_I = %le",
            &Isc,&i,
            &DbleVal[0]) == 3) {
            if (Isc == AC->ID) {
               if (AC->EPS != NULL) {
                  AC->EPS[i].IMU_I = DbleVal[0];
               }
            }
         }

         if (sscanf(line,"SC[%ld].AC.EPS[%ld].StarTracker_I = %le",
            &Isc,&i,
            &DbleVal[0]) == 3) {
            if (Isc == AC->ID) {
               if (AC->EPS != NULL) {
                  AC->EPS[i].StarTracker_I = DbleVal[0];
               }
            }
         }

         if (sscanf(line,"SC[%ld].AC.EPS[%ld].MTR_I = %le",
            &Isc,&i,
            &DbleVal[0]) == 3) {
            if (Isc == AC->ID) {
               if (AC->EPS != NULL) {
                  AC->EPS[i].MTR_I = DbleVal[0];
               }
            }
         }

         if (sscanf(line,"SC[%ld].AC.EPS[%ld].CSS_I = %le",
            &Isc,&i,
            &DbleVal[0]) == 3) {
            if (Isc == AC->ID) {
               if (AC->EPS != NULL) {
                  AC->EPS[i].CSS_I = DbleVal[0];
               }
            }
         }

         if (sscanf(line,"SC[%ld].AC.EPS[%ld].FSS_I = %le",
            &Isc,&i,
            &DbleVal[0]) == 3) {
            if (Isc == AC->ID) {
               if (AC->EPS != NULL) {
                  AC->EPS[i].FSS_I = DbleVal[0];
               }
            }
         }

         if (sscanf(line,"SC[%ld].AC.EPS[%ld].ADCS_I = %le",
            &Isc,&i,
            &DbleVal[0]) == 3) {
            if (Isc == AC->ID) {
               if (AC->EPS != NULL) {
                  AC->EPS[i].ADCS_I = DbleVal[0];
               }
            }
         }

         if (sscanf(line,"SC[%ld].AC.EPS[%ld].CDH_I = %le",
            &Isc,&i,
            &DbleVal[0]) == 3) {
            if (Isc == AC->ID) {
               if (AC->EPS != NULL) {
                  AC->EPS[i].CDH_I = DbleVal[0];
               }
            }
         }

         if (sscanf(line,"SC[%ld].AC.EPS[%ld].COM_I = %le",
            &Isc,&i,
            &DbleVal[0]) == 3) {
            if (Isc == AC->ID) {
               if (AC->EPS != NULL) {
                  AC->EPS[i].COM_I = DbleVal[0];
               }
            }
         }

         if (sscanf(line,"SC[%ld].AC.EPS[%ld].PAYLOAD_I = %le",
            &Isc,&i,
            &DbleVal[0]) == 3) {
            if (Isc == AC->ID) {
               if (AC->EPS != NULL) {
                  AC->EPS[i].PAYLOAD_I = DbleVal[0];
               }
            }
         }

         if (sscanf(line,"SC[%ld].AC.EPS[%ld].BATTERY_I = %le",
            &Isc,&i,
            &DbleVal[0]) == 3) {
            if (Isc == AC->ID) {
               if (AC->EPS != NULL) {
                  AC->EPS[i].BATTERY_I = DbleVal[0];
               }
            }
         }


         if (sscanf(line,"SC[%ld].AC.EPS[%ld].MTR_V = %le",
            &Isc,&i,
            &DbleVal[0]) == 3) {
            if (Isc == AC->ID) {
               if (AC->EPS != NULL) {
                  AC->EPS[i].MTR_V = DbleVal[0];
               }
            }
         }

         if (sscanf(line,"SC[%ld].AC.EPS[%ld].Wheel_V = %le",
            &Isc,&i,
            &DbleVal[0]) == 3) {
            if (Isc == AC->ID) {
               if (AC->EPS != NULL) {
                  AC->EPS[i].Wheel_V = DbleVal[0];
               }
            }
         }

         if (sscanf(line,"SC[%ld].AC.EPS[%ld].IMU_V = %le",
            &Isc,&i,
            &DbleVal[0]) == 3) {
            if (Isc == AC->ID) {
               if (AC->EPS != NULL) {
                  AC->EPS[i].IMU_V = DbleVal[0];
               }
            }
         }

         if (sscanf(line,"SC[%ld].AC.EPS[%ld].StarTracker_V = %le",
            &Isc,&i,
            &DbleVal[0]) == 3) {
            if (Isc == AC->ID) {
               if (AC->EPS != NULL) {
                  AC->EPS[i].StarTracker_V = DbleVal[0];
               }
            }
         }

         if (sscanf(line,"SC[%ld].AC.EPS[%ld].CSS_V = %le",
            &Isc,&i,
            &DbleVal[0]) == 3) {
            if (Isc == AC->ID) {
               if (AC->EPS != NULL) {
                  AC->EPS[i].CSS_V = DbleVal[0];
               }
            }
         }

         if (sscanf(line,"SC[%ld].AC.EPS[%ld].FSS_V = %le",
            &Isc,&i,
            &DbleVal[0]) == 3) {
            if (Isc == AC->ID) {
               if (AC->EPS != NULL) {
                  AC->EPS[i].FSS_V = DbleVal[0];
               }
            }
         }

         if (sscanf(line,"SC[%ld].AC.EPS[%ld].ADCS_V = %le",
            &Isc,&i,
            &DbleVal[0]) == 3) {
            if (Isc == AC->ID) {
               if (AC->EPS != NULL) {
                  AC->EPS[i].ADCS_V = DbleVal[0];
               }
            }
         }

         if (sscanf(line,"SC[%ld].AC.EPS[%ld].COM_V = %le",
            &Isc,&i,
            &DbleVal[0]) == 3) {
            if (Isc == AC->ID) {
               if (AC->EPS != NULL) {
                  AC->EPS[i].COM_V = DbleVal[0];
               }
            }
         }

         if (sscanf(line,"SC[%ld].AC.EPS[%ld].CDH_V = %le",
            &Isc,&i,
            &DbleVal[0]) == 3) {
            if (Isc == AC->ID) {
               if (AC->EPS != NULL) {
                  AC->EPS[i].CDH_V = DbleVal[0];
               }
            }
         }

         if (sscanf(line,"SC[%ld].AC.EPS[%ld].PAYLOAD_V = %le",
            &Isc,&i,
            &DbleVal[0]) == 3) {
            if (Isc == AC->ID) {
               if (AC->EPS != NULL) {
                  AC->EPS[i].PAYLOAD_V = DbleVal[0];
               }
            }
         }

         if (sscanf(line,"SC[%ld].AC.EPS[%ld].BATTERY_V = %le",
            &Isc,&i,
            &DbleVal[0]) == 3) {
            if (Isc == AC->ID) {
               if (AC->EPS != NULL) {
                  AC->EPS[i].BATTERY_V = DbleVal[0];
               }
            }
         }

         if (sscanf(line,"SC[%ld].AC.EPS[%ld].BATTERY_SOC = %le",
            &Isc,&i,
            &DbleVal[0]) == 3) {
            if (Isc == AC->ID) {
               if (AC->EPS != NULL) {
                  AC->EPS[i].BATTERY_SOC = DbleVal[0];
               }
            }
         }

         if (sscanf(line,"SC[%ld].AC.EPS[%ld].Wheel_Switch = %ld",
            &Isc,&i,
            &LongVal[0]) == 3) {
            if (Isc == AC->ID) {
               if (AC->EPS != NULL) {
                  AC->EPS[i].Wheel_Switch = LongVal[0];
               }
            }
         }

         if (sscanf(line,"SC[%ld].AC.EPS[%ld].IMU_Switch = %ld",
            &Isc,&i,
            &LongVal[0]) == 3) {
            if (Isc == AC->ID) {
               if (AC->EPS != NULL) {
                  AC->EPS[i].IMU_Switch = LongVal[0];
               }
            }
         }

         if (sscanf(line,"SC[%ld].AC.EPS[%ld].StarTracker_Switch = %ld",
            &Isc,&i,
            &LongVal[0]) == 3) {
            if (Isc == AC->ID) {
               if (AC->EPS != NULL) {
                  AC->EPS[i].StarTracker_Switch = LongVal[0];
               }
            }
         }

         if (sscanf(line,"SC[%ld].AC.EPS[%ld].MTR_Switch = %ld",
            &Isc,&i,
            &LongVal[0]) == 3) {
            if (Isc == AC->ID) {
               if (AC->EPS != NULL) {
                  AC->EPS[i].MTR_Switch = LongVal[0];
               }
            }
         }

         if (sscanf(line,"SC[%ld].AC.EPS[%ld].CSS_Switch = %ld",
            &Isc,&i,
            &LongVal[0]) == 3) {
            if (Isc == AC->ID) {
               if (AC->EPS != NULL) {
                  AC->EPS[i].CSS_Switch = LongVal[0];
               }
            }
         }

         if (sscanf(line,"SC[%ld].AC.EPS[%ld].FSS_Switch = %ld",
            &Isc,&i,
            &LongVal[0]) == 3) {
            if (Isc == AC->ID) {
               if (AC->EPS != NULL) {
                  AC->EPS[i].FSS_Switch = LongVal[0];
               }
            }
         }

         if (sscanf(line,"SC[%ld].AC.EPS[%ld].ADCS_Switch = %ld",
            &Isc,&i,
            &LongVal[0]) == 3) {
            if (Isc == AC->ID) {
               if (AC->EPS != NULL) {
                  AC->EPS[i].ADCS_Switch = LongVal[0];
               }
            }
         }

         if (sscanf(line,"SC[%ld].AC.EPS[%ld].COM_Switch = %ld",
            &Isc,&i,
            &LongVal[0]) == 3) {
            if (Isc == AC->ID) {
               if (AC->EPS != NULL) {
                  AC->EPS[i].COM_Switch = LongVal[0];
               }
            }
         }

         if (sscanf(line,"SC[%ld].AC.EPS[%ld].PAYLOAD_Switch = %ld",
            &Isc,&i,
            &LongVal[0]) == 3) {
            if (Isc == AC->ID) {
               if (AC->EPS != NULL) {
                  AC->EPS[i].PAYLOAD_Switch = LongVal[0];
               }
            }
         }

         if (sscanf(line,"SC[%ld].AC.SolArr[%ld].Valid = %ld",
            &Isc,&i,
            &LongVal[0]) == 3) {
            if (Isc == AC->ID) {
               if (AC->SolArr != NULL) {
                  AC->SolArr[i].Valid = LongVal[0];
               }
            }
         }

         if (sscanf(line,"SC[%ld].AC.SolArr[%ld].PowerOut = %le",
            &Isc,&i,
            &DbleVal[0]) == 3) {
            if (Isc == AC->ID) {
               if (AC->SolArr != NULL) {
                  AC->SolArr[i].PowerOut = DbleVal[0];
               }
            }
         }

         if (sscanf(line,"SC[%ld].AC.SolArr[%ld].CurrentOut = %le",
            &Isc,&i,
            &DbleVal[0]) == 3) {
            if (Isc == AC->ID) {
               if (AC->SolArr != NULL) {
                  AC->SolArr[i].CurrentOut = DbleVal[0];
               }
            }
         }

         if (sscanf(line,"SC[%ld].AC.SolArr[%ld].Voltage = %le",
            &Isc,&i,
            &DbleVal[0]) == 3) {
            if (Isc == AC->ID) {
               if (AC->SolArr != NULL) {
                  AC->SolArr[i].Voltage = DbleVal[0];
               }
            }
         }

         if (sscanf(line,"SC[%ld].AC.Whl[%ld].J = %le",
            &Isc,&i,
            &DbleVal[0]) == 3) {
            if (Isc == AC->ID) {
               if (AC->Whl != NULL) {
                  AC->Whl[i].J = DbleVal[0];
               }
            }
         }

         if (sscanf(line,"SC[%ld].AC.Whl[%ld].w = %le",
            &Isc,&i,
            &DbleVal[0]) == 3) {
            if (Isc == AC->ID) {
               if (AC->Whl != NULL) {
                  AC->Whl[i].w = DbleVal[0];
               }
            }
         }

         if (sscanf(line,"SC[%ld].AC.Whl[%ld].H = %le",
            &Isc,&i,
            &DbleVal[0]) == 3) {
            if (Isc == AC->ID) {
               if (AC->Whl != NULL) {
                  AC->Whl[i].H = DbleVal[0];
               }
            }
         }

         if (AC->ParmLoadEnabled) {
            if (sscanf(line,"SC[%ld].AC.ID = %ld",
               &Isc,
               &LongVal[0]) == 2) {
               if (Isc == AC->ID) {
                  AC->ID = LongVal[0];
               }
            }

            if (sscanf(line,"SC[%ld].AC.EchoEnabled = %ld",
               &Isc,
               &LongVal[0]) == 2) {
               if (Isc == AC->ID) {
                  AC->EchoEnabled = LongVal[0];
               }
            }

            if (sscanf(line,"SC[%ld].AC.ParmLoadEnabled = %ld",
               &Isc,
               &LongVal[0]) == 2) {
               if (Isc == AC->ID) {
                  AC->ParmLoadEnabled = LongVal[0];
               }
            }

            if (sscanf(line,"SC[%ld].AC.ParmDumpEnabled = %ld",
               &Isc,
               &LongVal[0]) == 2) {
               if (Isc == AC->ID) {
                  AC->ParmDumpEnabled = LongVal[0];
               }
            }

            if (sscanf(line,"SC[%ld].AC.Nb = %ld",
               &Isc,
               &LongVal[0]) == 2) {
               if (Isc == AC->ID) {
                  AC->Nb = LongVal[0];
               }
            }

            if (sscanf(line,"SC[%ld].AC.Ng = %ld",
               &Isc,
               &LongVal[0]) == 2) {
               if (Isc == AC->ID) {
                  AC->Ng = LongVal[0];
               }
            }

            if (sscanf(line,"SC[%ld].AC.Nwhl = %ld",
               &Isc,
               &LongVal[0]) == 2) {
               if (Isc == AC->ID) {
                  AC->Nwhl = LongVal[0];
               }
            }

            if (sscanf(line,"SC[%ld].AC.Nmtb = %ld",
               &Isc,
               &LongVal[0]) == 2) {
               if (Isc == AC->ID) {
                  AC->Nmtb = LongVal[0];
               }
            }

            if (sscanf(line,"SC[%ld].AC.Nthr = %ld",
               &Isc,
               &LongVal[0]) == 2) {
               if (Isc == AC->ID) {
                  AC->Nthr = LongVal[0];
               }
            }

            if (sscanf(line,"SC[%ld].AC.Ncmg = %ld",
               &Isc,
               &LongVal[0]) == 2) {
               if (Isc == AC->ID) {
                  AC->Ncmg = LongVal[0];
               }
            }

            if (sscanf(line,"SC[%ld].AC.Ngyro = %ld",
               &Isc,
               &LongVal[0]) == 2) {
               if (Isc == AC->ID) {
                  AC->Ngyro = LongVal[0];
               }
            }

            if (sscanf(line,"SC[%ld].AC.Nmag = %ld",
               &Isc,
               &LongVal[0]) == 2) {
               if (Isc == AC->ID) {
                  AC->Nmag = LongVal[0];
               }
            }

            if (sscanf(line,"SC[%ld].AC.Ncss = %ld",
               &Isc,
               &LongVal[0]) == 2) {
               if (Isc == AC->ID) {
                  AC->Ncss = LongVal[0];
               }
            }

            if (sscanf(line,"SC[%ld].AC.Nfss = %ld",
               &Isc,
               &LongVal[0]) == 2) {
               if (Isc == AC->ID) {
                  AC->Nfss = LongVal[0];
               }
            }

            if (sscanf(line,"SC[%ld].AC.Nst = %ld",
               &Isc,
               &LongVal[0]) == 2) {
               if (Isc == AC->ID) {
                  AC->Nst = LongVal[0];
               }
            }

            if (sscanf(line,"SC[%ld].AC.Ngps = %ld",
               &Isc,
               &LongVal[0]) == 2) {
               if (Isc == AC->ID) {
                  AC->Ngps = LongVal[0];
               }
            }

            if (sscanf(line,"SC[%ld].AC.Nacc = %ld",
               &Isc,
               &LongVal[0]) == 2) {
               if (Isc == AC->ID) {
                  AC->Nacc = LongVal[0];
               }
            }

            if (sscanf(line,"SC[%ld].AC.Neps = %ld",
               &Isc,
               &LongVal[0]) == 2) {
               if (Isc == AC->ID) {
                  AC->Neps = LongVal[0];
               }
            }

            if (sscanf(line,"SC[%ld].AC.Nsolarr = %ld",
               &Isc,
               &LongVal[0]) == 2) {
               if (Isc == AC->ID) {
                  AC->Nsolarr = LongVal[0];
               }
            }

            if (sscanf(line,"SC[%ld].AC.mass = %le",
               &Isc,
               &DbleVal[0]) == 2) {
               if (Isc == AC->ID) {
                  AC->mass = DbleVal[0];
               }
            }

            if (sscanf(line,"SC[%ld].AC.cm = %le %le %le",
               &Isc,
               &DbleVal[0],
               &DbleVal[1],
               &DbleVal[2]) == 4) {
               if (Isc == AC->ID) {
                  AC->cm[0] = DbleVal[0];
                  AC->cm[1] = DbleVal[1];
                  AC->cm[2] = DbleVal[2];
               }
            }

            if (sscanf(line,"SC[%ld].AC.MOI = %le %le %le %le %le %le %le %le %le",
               &Isc,
               &DbleVal[0],
               &DbleVal[1],
               &DbleVal[2],
               &DbleVal[3],
               &DbleVal[4],
               &DbleVal[5],
               &DbleVal[6],
               &DbleVal[7],
               &DbleVal[8]) == 10) {
               if (Isc == AC->ID) {
                  AC->MOI[0][0] = DbleVal[0];
                  AC->MOI[0][1] = DbleVal[1];
                  AC->MOI[0][2] = DbleVal[2];
                  AC->MOI[1][0] = DbleVal[3];
                  AC->MOI[1][1] = DbleVal[4];
                  AC->MOI[1][2] = DbleVal[5];
                  AC->MOI[2][0] = DbleVal[6];
                  AC->MOI[2][1] = DbleVal[7];
                  AC->MOI[2][2] = DbleVal[8];
               }
            }

            if (sscanf(line,"SC[%ld].AC.B[%ld].mass = %le",
               &Isc,&i,
               &DbleVal[0]) == 3) {
               if (Isc == AC->ID) {
                  if (AC->B != NULL) {
                     AC->B[i].mass = DbleVal[0];
                  }
               }
            }

            if (sscanf(line,"SC[%ld].AC.B[%ld].cm = %le %le %le",
               &Isc,&i,
               &DbleVal[0],
               &DbleVal[1],
               &DbleVal[2]) == 5) {
               if (Isc == AC->ID) {
                  if (AC->B != NULL) {
                     AC->B[i].cm[0] = DbleVal[0];
                     AC->B[i].cm[1] = DbleVal[1];
                     AC->B[i].cm[2] = DbleVal[2];
                  }
               }
            }

            if (sscanf(line,"SC[%ld].AC.B[%ld].MOI = %le %le %le %le %le %le %le %le %le",
               &Isc,&i,
               &DbleVal[0],
               &DbleVal[1],
               &DbleVal[2],
               &DbleVal[3],
               &DbleVal[4],
               &DbleVal[5],
               &DbleVal[6],
               &DbleVal[7],
               &DbleVal[8]) == 11) {
               if (Isc == AC->ID) {
                  if (AC->B != NULL) {
                     AC->B[i].MOI[0][0] = DbleVal[0];
                     AC->B[i].MOI[0][1] = DbleVal[1];
                     AC->B[i].MOI[0][2] = DbleVal[2];
                     AC->B[i].MOI[1][0] = DbleVal[3];
                     AC->B[i].MOI[1][1] = DbleVal[4];
                     AC->B[i].MOI[1][2] = DbleVal[5];
                     AC->B[i].MOI[2][0] = DbleVal[6];
                     AC->B[i].MOI[2][1] = DbleVal[7];
                     AC->B[i].MOI[2][2] = DbleVal[8];
                  }
               }
            }

            if (sscanf(line,"SC[%ld].AC.G[%ld].IsUnderActiveControl = %ld",
               &Isc,&i,
               &LongVal[0]) == 3) {
               if (Isc == AC->ID) {
                  if (AC->G != NULL) {
                     AC->G[i].IsUnderActiveControl = LongVal[0];
                  }
               }
            }

            if (sscanf(line,"SC[%ld].AC.G[%ld].IsSpherical = %ld",
               &Isc,&i,
               &LongVal[0]) == 3) {
               if (Isc == AC->ID) {
                  if (AC->G != NULL) {
                     AC->G[i].IsSpherical = LongVal[0];
                  }
               }
            }

            if (sscanf(line,"SC[%ld].AC.G[%ld].RotDOF = %ld",
               &Isc,&i,
               &LongVal[0]) == 3) {
               if (Isc == AC->ID) {
                  if (AC->G != NULL) {
                     AC->G[i].RotDOF = LongVal[0];
                  }
               }
            }

            if (sscanf(line,"SC[%ld].AC.G[%ld].TrnDOF = %ld",
               &Isc,&i,
               &LongVal[0]) == 3) {
               if (Isc == AC->ID) {
                  if (AC->G != NULL) {
                     AC->G[i].TrnDOF = LongVal[0];
                  }
               }
            }

            if (sscanf(line,"SC[%ld].AC.G[%ld].RotSeq = %ld",
               &Isc,&i,
               &LongVal[0]) == 3) {
               if (Isc == AC->ID) {
                  if (AC->G != NULL) {
                     AC->G[i].RotSeq = LongVal[0];
                  }
               }
            }

            if (sscanf(line,"SC[%ld].AC.G[%ld].TrnSeq = %ld",
               &Isc,&i,
               &LongVal[0]) == 3) {
               if (Isc == AC->ID) {
                  if (AC->G != NULL) {
                     AC->G[i].TrnSeq = LongVal[0];
                  }
               }
            }

            if (sscanf(line,"SC[%ld].AC.G[%ld].CGiBi = %le %le %le %le %le %le %le %le %le",
               &Isc,&i,
               &DbleVal[0],
               &DbleVal[1],
               &DbleVal[2],
               &DbleVal[3],
               &DbleVal[4],
               &DbleVal[5],
               &DbleVal[6],
               &DbleVal[7],
               &DbleVal[8]) == 11) {
               if (Isc == AC->ID) {
                  if (AC->G != NULL) {
                     AC->G[i].CGiBi[0][0] = DbleVal[0];
                     AC->G[i].CGiBi[0][1] = DbleVal[1];
                     AC->G[i].CGiBi[0][2] = DbleVal[2];
                     AC->G[i].CGiBi[1][0] = DbleVal[3];
                     AC->G[i].CGiBi[1][1] = DbleVal[4];
                     AC->G[i].CGiBi[1][2] = DbleVal[5];
                     AC->G[i].CGiBi[2][0] = DbleVal[6];
                     AC->G[i].CGiBi[2][1] = DbleVal[7];
                     AC->G[i].CGiBi[2][2] = DbleVal[8];
                  }
               }
            }

            if (sscanf(line,"SC[%ld].AC.G[%ld].CBoGo = %le %le %le %le %le %le %le %le %le",
               &Isc,&i,
               &DbleVal[0],
               &DbleVal[1],
               &DbleVal[2],
               &DbleVal[3],
               &DbleVal[4],
               &DbleVal[5],
               &DbleVal[6],
               &DbleVal[7],
               &DbleVal[8]) == 11) {
               if (Isc == AC->ID) {
                  if (AC->G != NULL) {
                     AC->G[i].CBoGo[0][0] = DbleVal[0];
                     AC->G[i].CBoGo[0][1] = DbleVal[1];
                     AC->G[i].CBoGo[0][2] = DbleVal[2];
                     AC->G[i].CBoGo[1][0] = DbleVal[3];
                     AC->G[i].CBoGo[1][1] = DbleVal[4];
                     AC->G[i].CBoGo[1][2] = DbleVal[5];
                     AC->G[i].CBoGo[2][0] = DbleVal[6];
                     AC->G[i].CBoGo[2][1] = DbleVal[7];
                     AC->G[i].CBoGo[2][2] = DbleVal[8];
                  }
               }
            }

            if (sscanf(line,"SC[%ld].AC.G[%ld].AngGain = %le %le %le",
               &Isc,&i,
               &DbleVal[0],
               &DbleVal[1],
               &DbleVal[2]) == 5) {
               if (Isc == AC->ID) {
                  if (AC->G != NULL) {
                     AC->G[i].AngGain[0] = DbleVal[0];
                     AC->G[i].AngGain[1] = DbleVal[1];
                     AC->G[i].AngGain[2] = DbleVal[2];
                  }
               }
            }

            if (sscanf(line,"SC[%ld].AC.G[%ld].AngRateGain = %le %le %le",
               &Isc,&i,
               &DbleVal[0],
               &DbleVal[1],
               &DbleVal[2]) == 5) {
               if (Isc == AC->ID) {
                  if (AC->G != NULL) {
                     AC->G[i].AngRateGain[0] = DbleVal[0];
                     AC->G[i].AngRateGain[1] = DbleVal[1];
                     AC->G[i].AngRateGain[2] = DbleVal[2];
                  }
               }
            }

            if (sscanf(line,"SC[%ld].AC.G[%ld].PosGain = %le %le %le",
               &Isc,&i,
               &DbleVal[0],
               &DbleVal[1],
               &DbleVal[2]) == 5) {
               if (Isc == AC->ID) {
                  if (AC->G != NULL) {
                     AC->G[i].PosGain[0] = DbleVal[0];
                     AC->G[i].PosGain[1] = DbleVal[1];
                     AC->G[i].PosGain[2] = DbleVal[2];
                  }
               }
            }

            if (sscanf(line,"SC[%ld].AC.G[%ld].PosRateGain = %le %le %le",
               &Isc,&i,
               &DbleVal[0],
               &DbleVal[1],
               &DbleVal[2]) == 5) {
               if (Isc == AC->ID) {
                  if (AC->G != NULL) {
                     AC->G[i].PosRateGain[0] = DbleVal[0];
                     AC->G[i].PosRateGain[1] = DbleVal[1];
                     AC->G[i].PosRateGain[2] = DbleVal[2];
                  }
               }
            }

            if (sscanf(line,"SC[%ld].AC.G[%ld].MaxAngRate = %le %le %le",
               &Isc,&i,
               &DbleVal[0],
               &DbleVal[1],
               &DbleVal[2]) == 5) {
               if (Isc == AC->ID) {
                  if (AC->G != NULL) {
                     AC->G[i].MaxAngRate[0] = DbleVal[0];
                     AC->G[i].MaxAngRate[1] = DbleVal[1];
                     AC->G[i].MaxAngRate[2] = DbleVal[2];
                  }
               }
            }

            if (sscanf(line,"SC[%ld].AC.G[%ld].MaxPosRate = %le %le %le",
               &Isc,&i,
               &DbleVal[0],
               &DbleVal[1],
               &DbleVal[2]) == 5) {
               if (Isc == AC->ID) {
                  if (AC->G != NULL) {
                     AC->G[i].MaxPosRate[0] = DbleVal[0];
                     AC->G[i].MaxPosRate[1] = DbleVal[1];
                     AC->G[i].MaxPosRate[2] = DbleVal[2];
                  }
               }
            }

            if (sscanf(line,"SC[%ld].AC.G[%ld].MaxTrq = %le %le %le",
               &Isc,&i,
               &DbleVal[0],
               &DbleVal[1],
               &DbleVal[2]) == 5) {
               if (Isc == AC->ID) {
                  if (AC->G != NULL) {
                     AC->G[i].MaxTrq[0] = DbleVal[0];
                     AC->G[i].MaxTrq[1] = DbleVal[1];
                     AC->G[i].MaxTrq[2] = DbleVal[2];
                  }
               }
            }

            if (sscanf(line,"SC[%ld].AC.G[%ld].MaxFrc = %le %le %le",
               &Isc,&i,
               &DbleVal[0],
               &DbleVal[1],
               &DbleVal[2]) == 5) {
               if (Isc == AC->ID) {
                  if (AC->G != NULL) {
                     AC->G[i].MaxFrc[0] = DbleVal[0];
                     AC->G[i].MaxFrc[1] = DbleVal[1];
                     AC->G[i].MaxFrc[2] = DbleVal[2];
                  }
               }
            }

            if (sscanf(line,"SC[%ld].AC.Gyro[%ld].Axis = %le %le %le",
               &Isc,&i,
               &DbleVal[0],
               &DbleVal[1],
               &DbleVal[2]) == 5) {
               if (Isc == AC->ID) {
                  if (AC->Gyro != NULL) {
                     AC->Gyro[i].Axis[0] = DbleVal[0];
                     AC->Gyro[i].Axis[1] = DbleVal[1];
                     AC->Gyro[i].Axis[2] = DbleVal[2];
                  }
               }
            }

            if (sscanf(line,"SC[%ld].AC.MAG[%ld].Axis = %le %le %le",
               &Isc,&i,
               &DbleVal[0],
               &DbleVal[1],
               &DbleVal[2]) == 5) {
               if (Isc == AC->ID) {
                  if (AC->MAG != NULL) {
                     AC->MAG[i].Axis[0] = DbleVal[0];
                     AC->MAG[i].Axis[1] = DbleVal[1];
                     AC->MAG[i].Axis[2] = DbleVal[2];
                  }
               }
            }

            if (sscanf(line,"SC[%ld].AC.CSS[%ld].Channel = %ld",
               &Isc,&i,
               &LongVal[0]) == 3) {
               if (Isc == AC->ID) {
                  if (AC->CSS != NULL) {
                     AC->CSS[i].Channel = LongVal[0];
                  }
               }
            }

            if (sscanf(line,"SC[%ld].AC.CSS[%ld].Body = %ld",
               &Isc,&i,
               &LongVal[0]) == 3) {
               if (Isc == AC->ID) {
                  if (AC->CSS != NULL) {
                     AC->CSS[i].Body = LongVal[0];
                  }
               }
            }

            if (sscanf(line,"SC[%ld].AC.CSS[%ld].Calibrated = %ld",
               &Isc,&i,
               &LongVal[0]) == 3) {
               if (Isc == AC->ID) {
                  if (AC->CSS != NULL) {
                     AC->CSS[i].Calibrated = LongVal[0];
                  }
               }
            }

            if (sscanf(line,"SC[%ld].AC.CSS[%ld].Axis = %le %le %le",
               &Isc,&i,
               &DbleVal[0],
               &DbleVal[1],
               &DbleVal[2]) == 5) {
               if (Isc == AC->ID) {
                  if (AC->CSS != NULL) {
                     AC->CSS[i].Axis[0] = DbleVal[0];
                     AC->CSS[i].Axis[1] = DbleVal[1];
                     AC->CSS[i].Axis[2] = DbleVal[2];
                  }
               }
            }

            if (sscanf(line,"SC[%ld].AC.CSS[%ld].Scale = %le",
               &Isc,&i,
               &DbleVal[0]) == 3) {
               if (Isc == AC->ID) {
                  if (AC->CSS != NULL) {
                     AC->CSS[i].Scale = DbleVal[0];
                  }
               }
            }

            if (sscanf(line,"SC[%ld].AC.CSS[%ld].IllumBackground = %le",
               &Isc,&i,
               &DbleVal[0]) == 3) {
               if (Isc == AC->ID) {
                  if (AC->CSS != NULL) {
                     AC->CSS[i].IllumBackground = DbleVal[0];
                  }
               }
            }

            if (sscanf(line,"SC[%ld].AC.FSS[%ld].qb = %le %le %le %le",
               &Isc,&i,
               &DbleVal[0],
               &DbleVal[1],
               &DbleVal[2],
               &DbleVal[3]) == 6) {
               if (Isc == AC->ID) {
                  if (AC->FSS != NULL) {
                     AC->FSS[i].qb[0] = DbleVal[0];
                     AC->FSS[i].qb[1] = DbleVal[1];
                     AC->FSS[i].qb[2] = DbleVal[2];
                     AC->FSS[i].qb[3] = DbleVal[3];
                  }
               }
            }

            if (sscanf(line,"SC[%ld].AC.FSS[%ld].CB = %le %le %le %le %le %le %le %le %le",
               &Isc,&i,
               &DbleVal[0],
               &DbleVal[1],
               &DbleVal[2],
               &DbleVal[3],
               &DbleVal[4],
               &DbleVal[5],
               &DbleVal[6],
               &DbleVal[7],
               &DbleVal[8]) == 11) {
               if (Isc == AC->ID) {
                  if (AC->FSS != NULL) {
                     AC->FSS[i].CB[0][0] = DbleVal[0];
                     AC->FSS[i].CB[0][1] = DbleVal[1];
                     AC->FSS[i].CB[0][2] = DbleVal[2];
                     AC->FSS[i].CB[1][0] = DbleVal[3];
                     AC->FSS[i].CB[1][1] = DbleVal[4];
                     AC->FSS[i].CB[1][2] = DbleVal[5];
                     AC->FSS[i].CB[2][0] = DbleVal[6];
                     AC->FSS[i].CB[2][1] = DbleVal[7];
                     AC->FSS[i].CB[2][2] = DbleVal[8];
                  }
               }
            }

            if (sscanf(line,"SC[%ld].AC.ST[%ld].qb = %le %le %le %le",
               &Isc,&i,
               &DbleVal[0],
               &DbleVal[1],
               &DbleVal[2],
               &DbleVal[3]) == 6) {
               if (Isc == AC->ID) {
                  if (AC->ST != NULL) {
                     AC->ST[i].qb[0] = DbleVal[0];
                     AC->ST[i].qb[1] = DbleVal[1];
                     AC->ST[i].qb[2] = DbleVal[2];
                     AC->ST[i].qb[3] = DbleVal[3];
                  }
               }
            }

            if (sscanf(line,"SC[%ld].AC.ST[%ld].CB = %le %le %le %le %le %le %le %le %le",
               &Isc,&i,
               &DbleVal[0],
               &DbleVal[1],
               &DbleVal[2],
               &DbleVal[3],
               &DbleVal[4],
               &DbleVal[5],
               &DbleVal[6],
               &DbleVal[7],
               &DbleVal[8]) == 11) {
               if (Isc == AC->ID) {
                  if (AC->ST != NULL) {
                     AC->ST[i].CB[0][0] = DbleVal[0];
                     AC->ST[i].CB[0][1] = DbleVal[1];
                     AC->ST[i].CB[0][2] = DbleVal[2];
                     AC->ST[i].CB[1][0] = DbleVal[3];
                     AC->ST[i].CB[1][1] = DbleVal[4];
                     AC->ST[i].CB[1][2] = DbleVal[5];
                     AC->ST[i].CB[2][0] = DbleVal[6];
                     AC->ST[i].CB[2][1] = DbleVal[7];
                     AC->ST[i].CB[2][2] = DbleVal[8];
                  }
               }
            }

            if (sscanf(line,"SC[%ld].AC.Accel[%ld].PosB = %le %le %le",
               &Isc,&i,
               &DbleVal[0],
               &DbleVal[1],
               &DbleVal[2]) == 5) {
               if (Isc == AC->ID) {
                  if (AC->Accel != NULL) {
                     AC->Accel[i].PosB[0] = DbleVal[0];
                     AC->Accel[i].PosB[1] = DbleVal[1];
                     AC->Accel[i].PosB[2] = DbleVal[2];
                  }
               }
            }

            if (sscanf(line,"SC[%ld].AC.Accel[%ld].Axis = %le %le %le",
               &Isc,&i,
               &DbleVal[0],
               &DbleVal[1],
               &DbleVal[2]) == 5) {
               if (Isc == AC->ID) {
                  if (AC->Accel != NULL) {
                     AC->Accel[i].Axis[0] = DbleVal[0];
                     AC->Accel[i].Axis[1] = DbleVal[1];
                     AC->Accel[i].Axis[2] = DbleVal[2];
                  }
               }
            }

            if (sscanf(line,"SC[%ld].AC.Whl[%ld].Axis = %le %le %le",
               &Isc,&i,
               &DbleVal[0],
               &DbleVal[1],
               &DbleVal[2]) == 5) {
               if (Isc == AC->ID) {
                  if (AC->Whl != NULL) {
                     AC->Whl[i].Axis[0] = DbleVal[0];
                     AC->Whl[i].Axis[1] = DbleVal[1];
                     AC->Whl[i].Axis[2] = DbleVal[2];
                  }
               }
            }

            if (sscanf(line,"SC[%ld].AC.Whl[%ld].DistVec = %le %le %le",
               &Isc,&i,
               &DbleVal[0],
               &DbleVal[1],
               &DbleVal[2]) == 5) {
               if (Isc == AC->ID) {
                  if (AC->Whl != NULL) {
                     AC->Whl[i].DistVec[0] = DbleVal[0];
                     AC->Whl[i].DistVec[1] = DbleVal[1];
                     AC->Whl[i].DistVec[2] = DbleVal[2];
                  }
               }
            }

            if (sscanf(line,"SC[%ld].AC.Whl[%ld].Tmax = %le",
               &Isc,&i,
               &DbleVal[0]) == 3) {
               if (Isc == AC->ID) {
                  if (AC->Whl != NULL) {
                     AC->Whl[i].Tmax = DbleVal[0];
                  }
               }
            }

            if (sscanf(line,"SC[%ld].AC.Whl[%ld].Hmax = %le",
               &Isc,&i,
               &DbleVal[0]) == 3) {
               if (Isc == AC->ID) {
                  if (AC->Whl != NULL) {
                     AC->Whl[i].Hmax = DbleVal[0];
                  }
               }
            }

            if (sscanf(line,"SC[%ld].AC.MTB[%ld].Axis = %le %le %le",
               &Isc,&i,
               &DbleVal[0],
               &DbleVal[1],
               &DbleVal[2]) == 5) {
               if (Isc == AC->ID) {
                  if (AC->MTB != NULL) {
                     AC->MTB[i].Axis[0] = DbleVal[0];
                     AC->MTB[i].Axis[1] = DbleVal[1];
                     AC->MTB[i].Axis[2] = DbleVal[2];
                  }
               }
            }

            if (sscanf(line,"SC[%ld].AC.MTB[%ld].DistVec = %le %le %le",
               &Isc,&i,
               &DbleVal[0],
               &DbleVal[1],
               &DbleVal[2]) == 5) {
               if (Isc == AC->ID) {
                  if (AC->MTB != NULL) {
                     AC->MTB[i].DistVec[0] = DbleVal[0];
                     AC->MTB[i].DistVec[1] = DbleVal[1];
                     AC->MTB[i].DistVec[2] = DbleVal[2];
                  }
               }
            }

            if (sscanf(line,"SC[%ld].AC.MTB[%ld].Mmax = %le",
               &Isc,&i,
               &DbleVal[0]) == 3) {
               if (Isc == AC->ID) {
                  if (AC->MTB != NULL) {
                     AC->MTB[i].Mmax = DbleVal[0];
                  }
               }
            }

            if (sscanf(line,"SC[%ld].AC.Thr[%ld].PosB = %le %le %le",
               &Isc,&i,
               &DbleVal[0],
               &DbleVal[1],
               &DbleVal[2]) == 5) {
               if (Isc == AC->ID) {
                  if (AC->Thr != NULL) {
                     AC->Thr[i].PosB[0] = DbleVal[0];
                     AC->Thr[i].PosB[1] = DbleVal[1];
                     AC->Thr[i].PosB[2] = DbleVal[2];
                  }
               }
            }

            if (sscanf(line,"SC[%ld].AC.Thr[%ld].Axis = %le %le %le",
               &Isc,&i,
               &DbleVal[0],
               &DbleVal[1],
               &DbleVal[2]) == 5) {
               if (Isc == AC->ID) {
                  if (AC->Thr != NULL) {
                     AC->Thr[i].Axis[0] = DbleVal[0];
                     AC->Thr[i].Axis[1] = DbleVal[1];
                     AC->Thr[i].Axis[2] = DbleVal[2];
                  }
               }
            }

            if (sscanf(line,"SC[%ld].AC.Thr[%ld].rxA = %le %le %le",
               &Isc,&i,
               &DbleVal[0],
               &DbleVal[1],
               &DbleVal[2]) == 5) {
               if (Isc == AC->ID) {
                  if (AC->Thr != NULL) {
                     AC->Thr[i].rxA[0] = DbleVal[0];
                     AC->Thr[i].rxA[1] = DbleVal[1];
                     AC->Thr[i].rxA[2] = DbleVal[2];
                  }
               }
            }

            if (sscanf(line,"SC[%ld].AC.Thr[%ld].Fmax = %le",
               &Isc,&i,
               &DbleVal[0]) == 3) {
               if (Isc == AC->ID) {
                  if (AC->Thr != NULL) {
                     AC->Thr[i].Fmax = DbleVal[0];
                  }
               }
            }

            if (sscanf(line,"SC[%ld].AC.FsCtrl.Kunl = %le",
               &Isc,
               &DbleVal[0]) == 2) {
               if (Isc == AC->ID) {
                  AC->FsCtrl.Kunl = DbleVal[0];
               }
            }

            if (sscanf(line,"SC[%ld].AC.FsCtrl.wc = %le",
               &Isc,
               &DbleVal[0]) == 2) {
               if (Isc == AC->ID) {
                  AC->FsCtrl.wc = DbleVal[0];
               }
            }

            if (sscanf(line,"SC[%ld].AC.FsCtrl.amax = %le",
               &Isc,
               &DbleVal[0]) == 2) {
               if (Isc == AC->ID) {
                  AC->FsCtrl.amax = DbleVal[0];
               }
            }

            if (sscanf(line,"SC[%ld].AC.FsCtrl.vmax = %le",
               &Isc,
               &DbleVal[0]) == 2) {
               if (Isc == AC->ID) {
                  AC->FsCtrl.vmax = DbleVal[0];
               }
            }

            if (sscanf(line,"SC[%ld].AC.FsCtrl.FrameTgt = %ld",
               &Isc,
               &LongVal[0]) == 2) {
               if (Isc == AC->ID) {
                  AC->FsCtrl.FrameTgt = LongVal[0];
               }
            }

            if (sscanf(line,"SC[%ld].AC.FsCtrl.qtr = %le %le %le %le",
               &Isc,
               &DbleVal[0],
               &DbleVal[1],
               &DbleVal[2],
               &DbleVal[3]) == 5) {
               if (Isc == AC->ID) {
                  AC->FsCtrl.qtr[0] = DbleVal[0];
                  AC->FsCtrl.qtr[1] = DbleVal[1];
                  AC->FsCtrl.qtr[2] = DbleVal[2];
                  AC->FsCtrl.qtr[3] = DbleVal[3];
               }
            }

            if (sscanf(line,"SC[%ld].AC.FsCtrl.qtn = %le %le %le %le",
               &Isc,
               &DbleVal[0],
               &DbleVal[1],
               &DbleVal[2],
               &DbleVal[3]) == 5) {
               if (Isc == AC->ID) {
                  AC->FsCtrl.qtn[0] = DbleVal[0];
                  AC->FsCtrl.qtn[1] = DbleVal[1];
                  AC->FsCtrl.qtn[2] = DbleVal[2];
                  AC->FsCtrl.qtn[3] = DbleVal[3];
               }
            }

            if (sscanf(line,"SC[%ld].AC.FsCtrl.qbl = %le %le %le %le",
               &Isc,
               &DbleVal[0],
               &DbleVal[1],
               &DbleVal[2],
               &DbleVal[3]) == 5) {
               if (Isc == AC->ID) {
                  AC->FsCtrl.qbl[0] = DbleVal[0];
                  AC->FsCtrl.qbl[1] = DbleVal[1];
                  AC->FsCtrl.qbl[2] = DbleVal[2];
                  AC->FsCtrl.qbl[3] = DbleVal[3];
               }
            }

            if (sscanf(line,"SC[%ld].AC.FsCtrl.qimu = %le %le %le %le",
               &Isc,
               &DbleVal[0],
               &DbleVal[1],
               &DbleVal[2],
               &DbleVal[3]) == 5) {
               if (Isc == AC->ID) {
                  AC->FsCtrl.qimu[0] = DbleVal[0];
                  AC->FsCtrl.qimu[1] = DbleVal[1];
                  AC->FsCtrl.qimu[2] = DbleVal[2];
                  AC->FsCtrl.qimu[3] = DbleVal[3];
               }
            }

            if (sscanf(line,"SC[%ld].AC.FsCtrl.SunYaw = %le",
               &Isc,
               &DbleVal[0]) == 2) {
               if (Isc == AC->ID) {
                  AC->FsCtrl.SunYaw = DbleVal[0];
               }
            }

            if (sscanf(line,"SC[%ld].AC.FsCtrl.SunYawTgt = %le",
               &Isc,
               &DbleVal[0]) == 2) {
               if (Isc == AC->ID) {
                  AC->FsCtrl.SunYawTgt = DbleVal[0];
               }
            }

            if (sscanf(line,"SC[%ld].AC.FsCtrl.SunYawDeadband = %le",
               &Isc,
               &DbleVal[0]) == 2) {
               if (Isc == AC->ID) {
                  AC->FsCtrl.SunYawDeadband = DbleVal[0];
               }
            }

            if (sscanf(line,"SC[%ld].AC.FsCtrl.SunYawRateDeadband = %le",
               &Isc,
               &DbleVal[0]) == 2) {
               if (Isc == AC->ID) {
                  AC->FsCtrl.SunYawRateDeadband = DbleVal[0];
               }
            }

            if (sscanf(line,"SC[%ld].AC.FsCtrl.SunYawError = %le",
               &Isc,
               &DbleVal[0]) == 2) {
               if (Isc == AC->ID) {
                  AC->FsCtrl.SunYawError = DbleVal[0];
               }
            }

         }


         if (!strncmp(line,"[EOF]",5)) {
            Done = 1;
            sprintf(line,"[EOF] reached\n");
         }
         if (Imsg >= MsgLen) {
            Done = 1;
            printf("Imsg limit exceeded\n");
         }
      }

      if (RequestTimeRefresh) {
         /* Update AC->Time */
         DOY2MD(Year,doy,&Month,&Day);
         AC->Time = DateToTime(Year,Month,Day,Hour,Minute,Second);
      }


/* .. Update SC MQTT states */

      AC->FsCtrl.SensorDataRecv = 1;
      AC->FsCtrl.SensorDataRecvCnt++;
}


/**********************************************************************/
size_t AcTypeToString(struct AcType *AC, char* Msg)
{

      long Isc,i;
      long MsgLen = 0;
      long LineLen;
      char line[512];

      Isc = AC->ID;

      sprintf(line,"SC[%ld].AC.Time = %18.12le\n",
         Isc,
         AC->Time);
      LineLen = strlen(line);
      memcpy(&Msg[MsgLen],line,LineLen);
      MsgLen += LineLen;
      if (AC->EchoEnabled) printf("%s",line);

      for(i=0;i<AC->Ng;i++) {
         sprintf(line,"SC[%ld].AC.G[%ld].Cmd.Ang = %18.12le %18.12le %18.12le\n",
            Isc,i,
            AC->G[i].Cmd.Ang[0],
            AC->G[i].Cmd.Ang[1],
            AC->G[i].Cmd.Ang[2]);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen],line,LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled) printf("%s",line);

      }

      for(i=0;i<AC->Neps;i++) {
         sprintf(line,"SC[%ld].AC.EPS[%ld].Wheel_Switch = %ld\n",
            Isc,i,
            AC->EPS[i].Wheel_Switch);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen],line,LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled) printf("%s",line);

         sprintf(line,"SC[%ld].AC.EPS[%ld].IMU_Switch = %ld\n",
            Isc,i,
            AC->EPS[i].IMU_Switch);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen],line,LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled) printf("%s",line);

         sprintf(line,"SC[%ld].AC.EPS[%ld].StarTracker_Switch = %ld\n",
            Isc,i,
            AC->EPS[i].StarTracker_Switch);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen],line,LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled) printf("%s",line);

         sprintf(line,"SC[%ld].AC.EPS[%ld].MTR_Switch = %ld\n",
            Isc,i,
            AC->EPS[i].MTR_Switch);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen],line,LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled) printf("%s",line);

         sprintf(line,"SC[%ld].AC.EPS[%ld].CSS_Switch = %ld\n",
            Isc,i,
            AC->EPS[i].CSS_Switch);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen],line,LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled) printf("%s",line);

         sprintf(line,"SC[%ld].AC.EPS[%ld].FSS_Switch = %ld\n",
            Isc,i,
            AC->EPS[i].FSS_Switch);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen],line,LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled) printf("%s",line);

         sprintf(line,"SC[%ld].AC.EPS[%ld].ADCS_Switch = %ld\n",
            Isc,i,
            AC->EPS[i].ADCS_Switch);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen],line,LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled) printf("%s",line);

         sprintf(line,"SC[%ld].AC.EPS[%ld].COM_Switch = %ld\n",
            Isc,i,
            AC->EPS[i].COM_Switch);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen],line,LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled) printf("%s",line);

         sprintf(line,"SC[%ld].AC.EPS[%ld].PAYLOAD_Switch = %ld\n",
            Isc,i,
            AC->EPS[i].PAYLOAD_Switch);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen],line,LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled) printf("%s",line);

      }

      for(i=0;i<AC->Nwhl;i++) {
         sprintf(line,"SC[%ld].AC.Whl[%ld].Tcmd = %18.12le\n",
            Isc,i,
            AC->Whl[i].Tcmd);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen],line,LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled) printf("%s",line);

      }

      for(i=0;i<AC->Nmtb;i++) {
         sprintf(line,"SC[%ld].AC.MTB[%ld].Mcmd = %18.12le\n",
            Isc,i,
            AC->MTB[i].Mcmd);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen],line,LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled) printf("%s",line);

      }

      for(i=0;i<AC->Nthr;i++) {
         sprintf(line,"SC[%ld].AC.Thr[%ld].PulseWidthCmd = %18.12le\n",
            Isc,i,
            AC->Thr[i].PulseWidthCmd);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen],line,LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled) printf("%s",line);

      }

      sprintf(line,"SC[%ld].AC.Cmd.Ang = %18.12le %18.12le %18.12le\n",
         Isc,
         AC->Cmd.Ang[0],
         AC->Cmd.Ang[1],
         AC->Cmd.Ang[2]);
      LineLen = strlen(line);
      memcpy(&Msg[MsgLen],line,LineLen);
      MsgLen += LineLen;
      if (AC->EchoEnabled) printf("%s",line);

      if (AC->ParmDumpEnabled) {
         sprintf(line,"SC[%ld].AC.ID = %ld\n",
            Isc,
            AC->ID);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen],line,LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled) printf("%s",line);

         sprintf(line,"SC[%ld].AC.EchoEnabled = %ld\n",
            Isc,
            AC->EchoEnabled);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen],line,LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled) printf("%s",line);

         sprintf(line,"SC[%ld].AC.ParmLoadEnabled = %ld\n",
            Isc,
            AC->ParmLoadEnabled);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen],line,LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled) printf("%s",line);

         sprintf(line,"SC[%ld].AC.ParmDumpEnabled = %ld\n",
            Isc,
            AC->ParmDumpEnabled);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen],line,LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled) printf("%s",line);

         sprintf(line,"SC[%ld].AC.Nb = %ld\n",
            Isc,
            AC->Nb);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen],line,LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled) printf("%s",line);

         sprintf(line,"SC[%ld].AC.Ng = %ld\n",
            Isc,
            AC->Ng);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen],line,LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled) printf("%s",line);

         sprintf(line,"SC[%ld].AC.Nwhl = %ld\n",
            Isc,
            AC->Nwhl);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen],line,LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled) printf("%s",line);

         sprintf(line,"SC[%ld].AC.Nmtb = %ld\n",
            Isc,
            AC->Nmtb);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen],line,LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled) printf("%s",line);

         sprintf(line,"SC[%ld].AC.Nthr = %ld\n",
            Isc,
            AC->Nthr);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen],line,LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled) printf("%s",line);

         sprintf(line,"SC[%ld].AC.Ncmg = %ld\n",
            Isc,
            AC->Ncmg);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen],line,LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled) printf("%s",line);

         sprintf(line,"SC[%ld].AC.Ngyro = %ld\n",
            Isc,
            AC->Ngyro);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen],line,LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled) printf("%s",line);

         sprintf(line,"SC[%ld].AC.Nmag = %ld\n",
            Isc,
            AC->Nmag);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen],line,LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled) printf("%s",line);

         sprintf(line,"SC[%ld].AC.Ncss = %ld\n",
            Isc,
            AC->Ncss);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen],line,LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled) printf("%s",line);

         sprintf(line,"SC[%ld].AC.Nfss = %ld\n",
            Isc,
            AC->Nfss);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen],line,LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled) printf("%s",line);

         sprintf(line,"SC[%ld].AC.Nst = %ld\n",
            Isc,
            AC->Nst);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen],line,LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled) printf("%s",line);

         sprintf(line,"SC[%ld].AC.Ngps = %ld\n",
            Isc,
            AC->Ngps);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen],line,LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled) printf("%s",line);

         sprintf(line,"SC[%ld].AC.Nacc = %ld\n",
            Isc,
            AC->Nacc);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen],line,LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled) printf("%s",line);

         sprintf(line,"SC[%ld].AC.Neps = %ld\n",
            Isc,
            AC->Neps);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen],line,LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled) printf("%s",line);

         sprintf(line,"SC[%ld].AC.Nsolarr = %ld\n",
            Isc,
            AC->Nsolarr);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen],line,LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled) printf("%s",line);

         sprintf(line,"SC[%ld].AC.mass = %18.12le\n",
            Isc,
            AC->mass);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen],line,LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled) printf("%s",line);

         sprintf(line,"SC[%ld].AC.cm = %18.12le %18.12le %18.12le\n",
            Isc,
            AC->cm[0],
            AC->cm[1],
            AC->cm[2]);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen],line,LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled) printf("%s",line);

         sprintf(line,"SC[%ld].AC.MOI = %18.12le %18.12le %18.12le %18.12le %18.12le %18.12le %18.12le %18.12le %18.12le\n",
            Isc,
            AC->MOI[0][0],
            AC->MOI[0][1],
            AC->MOI[0][2],
            AC->MOI[1][0],
            AC->MOI[1][1],
            AC->MOI[1][2],
            AC->MOI[2][0],
            AC->MOI[2][1],
            AC->MOI[2][2]);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen],line,LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled) printf("%s",line);

         for(i=0;i<AC->Nb;i++) {
            sprintf(line,"SC[%ld].AC.B[%ld].mass = %18.12le\n",
               Isc,i,
               AC->B[i].mass);
            LineLen = strlen(line);
            memcpy(&Msg[MsgLen],line,LineLen);
            MsgLen += LineLen;
            if (AC->EchoEnabled) printf("%s",line);

            sprintf(line,"SC[%ld].AC.B[%ld].cm = %18.12le %18.12le %18.12le\n",
               Isc,i,
               AC->B[i].cm[0],
               AC->B[i].cm[1],
               AC->B[i].cm[2]);
            LineLen = strlen(line);
            memcpy(&Msg[MsgLen],line,LineLen);
            MsgLen += LineLen;
            if (AC->EchoEnabled) printf("%s",line);

            sprintf(line,"SC[%ld].AC.B[%ld].MOI = %18.12le %18.12le %18.12le %18.12le %18.12le %18.12le %18.12le %18.12le %18.12le\n",
               Isc,i,
               AC->B[i].MOI[0][0],
               AC->B[i].MOI[0][1],
               AC->B[i].MOI[0][2],
               AC->B[i].MOI[1][0],
               AC->B[i].MOI[1][1],
               AC->B[i].MOI[1][2],
               AC->B[i].MOI[2][0],
               AC->B[i].MOI[2][1],
               AC->B[i].MOI[2][2]);
            LineLen = strlen(line);
            memcpy(&Msg[MsgLen],line,LineLen);
            MsgLen += LineLen;
            if (AC->EchoEnabled) printf("%s",line);

         }

         for(i=0;i<AC->Ng;i++) {
            sprintf(line,"SC[%ld].AC.G[%ld].IsUnderActiveControl = %ld\n",
               Isc,i,
               AC->G[i].IsUnderActiveControl);
            LineLen = strlen(line);
            memcpy(&Msg[MsgLen],line,LineLen);
            MsgLen += LineLen;
            if (AC->EchoEnabled) printf("%s",line);

            sprintf(line,"SC[%ld].AC.G[%ld].IsSpherical = %ld\n",
               Isc,i,
               AC->G[i].IsSpherical);
            LineLen = strlen(line);
            memcpy(&Msg[MsgLen],line,LineLen);
            MsgLen += LineLen;
            if (AC->EchoEnabled) printf("%s",line);

            sprintf(line,"SC[%ld].AC.G[%ld].RotDOF = %ld\n",
               Isc,i,
               AC->G[i].RotDOF);
            LineLen = strlen(line);
            memcpy(&Msg[MsgLen],line,LineLen);
            MsgLen += LineLen;
            if (AC->EchoEnabled) printf("%s",line);

            sprintf(line,"SC[%ld].AC.G[%ld].TrnDOF = %ld\n",
               Isc,i,
               AC->G[i].TrnDOF);
            LineLen = strlen(line);
            memcpy(&Msg[MsgLen],line,LineLen);
            MsgLen += LineLen;
            if (AC->EchoEnabled) printf("%s",line);

            sprintf(line,"SC[%ld].AC.G[%ld].RotSeq = %ld\n",
               Isc,i,
               AC->G[i].RotSeq);
            LineLen = strlen(line);
            memcpy(&Msg[MsgLen],line,LineLen);
            MsgLen += LineLen;
            if (AC->EchoEnabled) printf("%s",line);

            sprintf(line,"SC[%ld].AC.G[%ld].TrnSeq = %ld\n",
               Isc,i,
               AC->G[i].TrnSeq);
            LineLen = strlen(line);
            memcpy(&Msg[MsgLen],line,LineLen);
            MsgLen += LineLen;
            if (AC->EchoEnabled) printf("%s",line);

            sprintf(line,"SC[%ld].AC.G[%ld].CGiBi = %18.12le %18.12le %18.12le %18.12le %18.12le %18.12le %18.12le %18.12le %18.12le\n",
               Isc,i,
               AC->G[i].CGiBi[0][0],
               AC->G[i].CGiBi[0][1],
               AC->G[i].CGiBi[0][2],
               AC->G[i].CGiBi[1][0],
               AC->G[i].CGiBi[1][1],
               AC->G[i].CGiBi[1][2],
               AC->G[i].CGiBi[2][0],
               AC->G[i].CGiBi[2][1],
               AC->G[i].CGiBi[2][2]);
            LineLen = strlen(line);
            memcpy(&Msg[MsgLen],line,LineLen);
            MsgLen += LineLen;
            if (AC->EchoEnabled) printf("%s",line);

            sprintf(line,"SC[%ld].AC.G[%ld].CBoGo = %18.12le %18.12le %18.12le %18.12le %18.12le %18.12le %18.12le %18.12le %18.12le\n",
               Isc,i,
               AC->G[i].CBoGo[0][0],
               AC->G[i].CBoGo[0][1],
               AC->G[i].CBoGo[0][2],
               AC->G[i].CBoGo[1][0],
               AC->G[i].CBoGo[1][1],
               AC->G[i].CBoGo[1][2],
               AC->G[i].CBoGo[2][0],
               AC->G[i].CBoGo[2][1],
               AC->G[i].CBoGo[2][2]);
            LineLen = strlen(line);
            memcpy(&Msg[MsgLen],line,LineLen);
            MsgLen += LineLen;
            if (AC->EchoEnabled) printf("%s",line);

            sprintf(line,"SC[%ld].AC.G[%ld].AngGain = %18.12le %18.12le %18.12le\n",
               Isc,i,
               AC->G[i].AngGain[0],
               AC->G[i].AngGain[1],
               AC->G[i].AngGain[2]);
            LineLen = strlen(line);
            memcpy(&Msg[MsgLen],line,LineLen);
            MsgLen += LineLen;
            if (AC->EchoEnabled) printf("%s",line);

            sprintf(line,"SC[%ld].AC.G[%ld].AngRateGain = %18.12le %18.12le %18.12le\n",
               Isc,i,
               AC->G[i].AngRateGain[0],
               AC->G[i].AngRateGain[1],
               AC->G[i].AngRateGain[2]);
            LineLen = strlen(line);
            memcpy(&Msg[MsgLen],line,LineLen);
            MsgLen += LineLen;
            if (AC->EchoEnabled) printf("%s",line);

            sprintf(line,"SC[%ld].AC.G[%ld].PosGain = %18.12le %18.12le %18.12le\n",
               Isc,i,
               AC->G[i].PosGain[0],
               AC->G[i].PosGain[1],
               AC->G[i].PosGain[2]);
            LineLen = strlen(line);
            memcpy(&Msg[MsgLen],line,LineLen);
            MsgLen += LineLen;
            if (AC->EchoEnabled) printf("%s",line);

            sprintf(line,"SC[%ld].AC.G[%ld].PosRateGain = %18.12le %18.12le %18.12le\n",
               Isc,i,
               AC->G[i].PosRateGain[0],
               AC->G[i].PosRateGain[1],
               AC->G[i].PosRateGain[2]);
            LineLen = strlen(line);
            memcpy(&Msg[MsgLen],line,LineLen);
            MsgLen += LineLen;
            if (AC->EchoEnabled) printf("%s",line);

            sprintf(line,"SC[%ld].AC.G[%ld].MaxAngRate = %18.12le %18.12le %18.12le\n",
               Isc,i,
               AC->G[i].MaxAngRate[0],
               AC->G[i].MaxAngRate[1],
               AC->G[i].MaxAngRate[2]);
            LineLen = strlen(line);
            memcpy(&Msg[MsgLen],line,LineLen);
            MsgLen += LineLen;
            if (AC->EchoEnabled) printf("%s",line);

            sprintf(line,"SC[%ld].AC.G[%ld].MaxPosRate = %18.12le %18.12le %18.12le\n",
               Isc,i,
               AC->G[i].MaxPosRate[0],
               AC->G[i].MaxPosRate[1],
               AC->G[i].MaxPosRate[2]);
            LineLen = strlen(line);
            memcpy(&Msg[MsgLen],line,LineLen);
            MsgLen += LineLen;
            if (AC->EchoEnabled) printf("%s",line);

            sprintf(line,"SC[%ld].AC.G[%ld].MaxTrq = %18.12le %18.12le %18.12le\n",
               Isc,i,
               AC->G[i].MaxTrq[0],
               AC->G[i].MaxTrq[1],
               AC->G[i].MaxTrq[2]);
            LineLen = strlen(line);
            memcpy(&Msg[MsgLen],line,LineLen);
            MsgLen += LineLen;
            if (AC->EchoEnabled) printf("%s",line);

            sprintf(line,"SC[%ld].AC.G[%ld].MaxFrc = %18.12le %18.12le %18.12le\n",
               Isc,i,
               AC->G[i].MaxFrc[0],
               AC->G[i].MaxFrc[1],
               AC->G[i].MaxFrc[2]);
            LineLen = strlen(line);
            memcpy(&Msg[MsgLen],line,LineLen);
            MsgLen += LineLen;
            if (AC->EchoEnabled) printf("%s",line);

         }

         for(i=0;i<AC->Ngyro;i++) {
            sprintf(line,"SC[%ld].AC.Gyro[%ld].Axis = %18.12le %18.12le %18.12le\n",
               Isc,i,
               AC->Gyro[i].Axis[0],
               AC->Gyro[i].Axis[1],
               AC->Gyro[i].Axis[2]);
            LineLen = strlen(line);
            memcpy(&Msg[MsgLen],line,LineLen);
            MsgLen += LineLen;
            if (AC->EchoEnabled) printf("%s",line);

         }

         for(i=0;i<AC->Nmag;i++) {
            sprintf(line,"SC[%ld].AC.MAG[%ld].Axis = %18.12le %18.12le %18.12le\n",
               Isc,i,
               AC->MAG[i].Axis[0],
               AC->MAG[i].Axis[1],
               AC->MAG[i].Axis[2]);
            LineLen = strlen(line);
            memcpy(&Msg[MsgLen],line,LineLen);
            MsgLen += LineLen;
            if (AC->EchoEnabled) printf("%s",line);

         }

         for(i=0;i<AC->Ncss;i++) {
            sprintf(line,"SC[%ld].AC.CSS[%ld].Channel = %ld\n",
               Isc,i,
               AC->CSS[i].Channel);
            LineLen = strlen(line);
            memcpy(&Msg[MsgLen],line,LineLen);
            MsgLen += LineLen;
            if (AC->EchoEnabled) printf("%s",line);

            sprintf(line,"SC[%ld].AC.CSS[%ld].Body = %ld\n",
               Isc,i,
               AC->CSS[i].Body);
            LineLen = strlen(line);
            memcpy(&Msg[MsgLen],line,LineLen);
            MsgLen += LineLen;
            if (AC->EchoEnabled) printf("%s",line);

            sprintf(line,"SC[%ld].AC.CSS[%ld].Calibrated = %ld\n",
               Isc,i,
               AC->CSS[i].Calibrated);
            LineLen = strlen(line);
            memcpy(&Msg[MsgLen],line,LineLen);
            MsgLen += LineLen;
            if (AC->EchoEnabled) printf("%s",line);

            sprintf(line,"SC[%ld].AC.CSS[%ld].Axis = %18.12le %18.12le %18.12le\n",
               Isc,i,
               AC->CSS[i].Axis[0],
               AC->CSS[i].Axis[1],
               AC->CSS[i].Axis[2]);
            LineLen = strlen(line);
            memcpy(&Msg[MsgLen],line,LineLen);
            MsgLen += LineLen;
            if (AC->EchoEnabled) printf("%s",line);

            sprintf(line,"SC[%ld].AC.CSS[%ld].Scale = %18.12le\n",
               Isc,i,
               AC->CSS[i].Scale);
            LineLen = strlen(line);
            memcpy(&Msg[MsgLen],line,LineLen);
            MsgLen += LineLen;
            if (AC->EchoEnabled) printf("%s",line);

            sprintf(line,"SC[%ld].AC.CSS[%ld].IllumBackground = %18.12le\n",
               Isc,i,
               AC->CSS[i].IllumBackground);
            LineLen = strlen(line);
            memcpy(&Msg[MsgLen],line,LineLen);
            MsgLen += LineLen;
            if (AC->EchoEnabled) printf("%s",line);

         }

         for(i=0;i<AC->Nfss;i++) {
            sprintf(line,"SC[%ld].AC.FSS[%ld].qb = %18.12le %18.12le %18.12le %18.12le\n",
               Isc,i,
               AC->FSS[i].qb[0],
               AC->FSS[i].qb[1],
               AC->FSS[i].qb[2],
               AC->FSS[i].qb[3]);
            LineLen = strlen(line);
            memcpy(&Msg[MsgLen],line,LineLen);
            MsgLen += LineLen;
            if (AC->EchoEnabled) printf("%s",line);

            sprintf(line,"SC[%ld].AC.FSS[%ld].CB = %18.12le %18.12le %18.12le %18.12le %18.12le %18.12le %18.12le %18.12le %18.12le\n",
               Isc,i,
               AC->FSS[i].CB[0][0],
               AC->FSS[i].CB[0][1],
               AC->FSS[i].CB[0][2],
               AC->FSS[i].CB[1][0],
               AC->FSS[i].CB[1][1],
               AC->FSS[i].CB[1][2],
               AC->FSS[i].CB[2][0],
               AC->FSS[i].CB[2][1],
               AC->FSS[i].CB[2][2]);
            LineLen = strlen(line);
            memcpy(&Msg[MsgLen],line,LineLen);
            MsgLen += LineLen;
            if (AC->EchoEnabled) printf("%s",line);

         }

         for(i=0;i<AC->Nst;i++) {
            sprintf(line,"SC[%ld].AC.ST[%ld].qb = %18.12le %18.12le %18.12le %18.12le\n",
               Isc,i,
               AC->ST[i].qb[0],
               AC->ST[i].qb[1],
               AC->ST[i].qb[2],
               AC->ST[i].qb[3]);
            LineLen = strlen(line);
            memcpy(&Msg[MsgLen],line,LineLen);
            MsgLen += LineLen;
            if (AC->EchoEnabled) printf("%s",line);

            sprintf(line,"SC[%ld].AC.ST[%ld].CB = %18.12le %18.12le %18.12le %18.12le %18.12le %18.12le %18.12le %18.12le %18.12le\n",
               Isc,i,
               AC->ST[i].CB[0][0],
               AC->ST[i].CB[0][1],
               AC->ST[i].CB[0][2],
               AC->ST[i].CB[1][0],
               AC->ST[i].CB[1][1],
               AC->ST[i].CB[1][2],
               AC->ST[i].CB[2][0],
               AC->ST[i].CB[2][1],
               AC->ST[i].CB[2][2]);
            LineLen = strlen(line);
            memcpy(&Msg[MsgLen],line,LineLen);
            MsgLen += LineLen;
            if (AC->EchoEnabled) printf("%s",line);

         }

         for(i=0;i<AC->Nacc;i++) {
            sprintf(line,"SC[%ld].AC.Accel[%ld].PosB = %18.12le %18.12le %18.12le\n",
               Isc,i,
               AC->Accel[i].PosB[0],
               AC->Accel[i].PosB[1],
               AC->Accel[i].PosB[2]);
            LineLen = strlen(line);
            memcpy(&Msg[MsgLen],line,LineLen);
            MsgLen += LineLen;
            if (AC->EchoEnabled) printf("%s",line);

            sprintf(line,"SC[%ld].AC.Accel[%ld].Axis = %18.12le %18.12le %18.12le\n",
               Isc,i,
               AC->Accel[i].Axis[0],
               AC->Accel[i].Axis[1],
               AC->Accel[i].Axis[2]);
            LineLen = strlen(line);
            memcpy(&Msg[MsgLen],line,LineLen);
            MsgLen += LineLen;
            if (AC->EchoEnabled) printf("%s",line);

         }

         for(i=0;i<AC->Nwhl;i++) {
            sprintf(line,"SC[%ld].AC.Whl[%ld].Axis = %18.12le %18.12le %18.12le\n",
               Isc,i,
               AC->Whl[i].Axis[0],
               AC->Whl[i].Axis[1],
               AC->Whl[i].Axis[2]);
            LineLen = strlen(line);
            memcpy(&Msg[MsgLen],line,LineLen);
            MsgLen += LineLen;
            if (AC->EchoEnabled) printf("%s",line);

            sprintf(line,"SC[%ld].AC.Whl[%ld].DistVec = %18.12le %18.12le %18.12le\n",
               Isc,i,
               AC->Whl[i].DistVec[0],
               AC->Whl[i].DistVec[1],
               AC->Whl[i].DistVec[2]);
            LineLen = strlen(line);
            memcpy(&Msg[MsgLen],line,LineLen);
            MsgLen += LineLen;
            if (AC->EchoEnabled) printf("%s",line);

            sprintf(line,"SC[%ld].AC.Whl[%ld].Tmax = %18.12le\n",
               Isc,i,
               AC->Whl[i].Tmax);
            LineLen = strlen(line);
            memcpy(&Msg[MsgLen],line,LineLen);
            MsgLen += LineLen;
            if (AC->EchoEnabled) printf("%s",line);

            sprintf(line,"SC[%ld].AC.Whl[%ld].Hmax = %18.12le\n",
               Isc,i,
               AC->Whl[i].Hmax);
            LineLen = strlen(line);
            memcpy(&Msg[MsgLen],line,LineLen);
            MsgLen += LineLen;
            if (AC->EchoEnabled) printf("%s",line);

         }

         for(i=0;i<AC->Nmtb;i++) {
            sprintf(line,"SC[%ld].AC.MTB[%ld].Axis = %18.12le %18.12le %18.12le\n",
               Isc,i,
               AC->MTB[i].Axis[0],
               AC->MTB[i].Axis[1],
               AC->MTB[i].Axis[2]);
            LineLen = strlen(line);
            memcpy(&Msg[MsgLen],line,LineLen);
            MsgLen += LineLen;
            if (AC->EchoEnabled) printf("%s",line);

            sprintf(line,"SC[%ld].AC.MTB[%ld].DistVec = %18.12le %18.12le %18.12le\n",
               Isc,i,
               AC->MTB[i].DistVec[0],
               AC->MTB[i].DistVec[1],
               AC->MTB[i].DistVec[2]);
            LineLen = strlen(line);
            memcpy(&Msg[MsgLen],line,LineLen);
            MsgLen += LineLen;
            if (AC->EchoEnabled) printf("%s",line);

            sprintf(line,"SC[%ld].AC.MTB[%ld].Mmax = %18.12le\n",
               Isc,i,
               AC->MTB[i].Mmax);
            LineLen = strlen(line);
            memcpy(&Msg[MsgLen],line,LineLen);
            MsgLen += LineLen;
            if (AC->EchoEnabled) printf("%s",line);

         }

         for(i=0;i<AC->Nthr;i++) {
            sprintf(line,"SC[%ld].AC.Thr[%ld].PosB = %18.12le %18.12le %18.12le\n",
               Isc,i,
               AC->Thr[i].PosB[0],
               AC->Thr[i].PosB[1],
               AC->Thr[i].PosB[2]);
            LineLen = strlen(line);
            memcpy(&Msg[MsgLen],line,LineLen);
            MsgLen += LineLen;
            if (AC->EchoEnabled) printf("%s",line);

            sprintf(line,"SC[%ld].AC.Thr[%ld].Axis = %18.12le %18.12le %18.12le\n",
               Isc,i,
               AC->Thr[i].Axis[0],
               AC->Thr[i].Axis[1],
               AC->Thr[i].Axis[2]);
            LineLen = strlen(line);
            memcpy(&Msg[MsgLen],line,LineLen);
            MsgLen += LineLen;
            if (AC->EchoEnabled) printf("%s",line);

            sprintf(line,"SC[%ld].AC.Thr[%ld].rxA = %18.12le %18.12le %18.12le\n",
               Isc,i,
               AC->Thr[i].rxA[0],
               AC->Thr[i].rxA[1],
               AC->Thr[i].rxA[2]);
            LineLen = strlen(line);
            memcpy(&Msg[MsgLen],line,LineLen);
            MsgLen += LineLen;
            if (AC->EchoEnabled) printf("%s",line);

            sprintf(line,"SC[%ld].AC.Thr[%ld].Fmax = %18.12le\n",
               Isc,i,
               AC->Thr[i].Fmax);
            LineLen = strlen(line);
            memcpy(&Msg[MsgLen],line,LineLen);
            MsgLen += LineLen;
            if (AC->EchoEnabled) printf("%s",line);

         }

         sprintf(line,"SC[%ld].AC.FsCtrl.Kunl = %18.12le\n",
            Isc,
            AC->FsCtrl.Kunl);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen],line,LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled) printf("%s",line);

         sprintf(line,"SC[%ld].AC.FsCtrl.wc = %18.12le\n",
            Isc,
            AC->FsCtrl.wc);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen],line,LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled) printf("%s",line);

         sprintf(line,"SC[%ld].AC.FsCtrl.amax = %18.12le\n",
            Isc,
            AC->FsCtrl.amax);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen],line,LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled) printf("%s",line);

         sprintf(line,"SC[%ld].AC.FsCtrl.vmax = %18.12le\n",
            Isc,
            AC->FsCtrl.vmax);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen],line,LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled) printf("%s",line);

         sprintf(line,"SC[%ld].AC.FsCtrl.FrameTgt = %ld\n",
            Isc,
            AC->FsCtrl.FrameTgt);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen],line,LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled) printf("%s",line);

         sprintf(line,"SC[%ld].AC.FsCtrl.qtr = %18.12le %18.12le %18.12le %18.12le\n",
            Isc,
            AC->FsCtrl.qtr[0],
            AC->FsCtrl.qtr[1],
            AC->FsCtrl.qtr[2],
            AC->FsCtrl.qtr[3]);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen],line,LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled) printf("%s",line);

         sprintf(line,"SC[%ld].AC.FsCtrl.qtn = %18.12le %18.12le %18.12le %18.12le\n",
            Isc,
            AC->FsCtrl.qtn[0],
            AC->FsCtrl.qtn[1],
            AC->FsCtrl.qtn[2],
            AC->FsCtrl.qtn[3]);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen],line,LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled) printf("%s",line);

         sprintf(line,"SC[%ld].AC.FsCtrl.qbl = %18.12le %18.12le %18.12le %18.12le\n",
            Isc,
            AC->FsCtrl.qbl[0],
            AC->FsCtrl.qbl[1],
            AC->FsCtrl.qbl[2],
            AC->FsCtrl.qbl[3]);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen],line,LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled) printf("%s",line);

         sprintf(line,"SC[%ld].AC.FsCtrl.qimu = %18.12le %18.12le %18.12le %18.12le\n",
            Isc,
            AC->FsCtrl.qimu[0],
            AC->FsCtrl.qimu[1],
            AC->FsCtrl.qimu[2],
            AC->FsCtrl.qimu[3]);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen],line,LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled) printf("%s",line);

         sprintf(line,"SC[%ld].AC.FsCtrl.SunYaw = %18.12le\n",
            Isc,
            AC->FsCtrl.SunYaw);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen],line,LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled) printf("%s",line);

         sprintf(line,"SC[%ld].AC.FsCtrl.SunYawTgt = %18.12le\n",
            Isc,
            AC->FsCtrl.SunYawTgt);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen],line,LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled) printf("%s",line);

         sprintf(line,"SC[%ld].AC.FsCtrl.SunYawDeadband = %18.12le\n",
            Isc,
            AC->FsCtrl.SunYawDeadband);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen],line,LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled) printf("%s",line);

         sprintf(line,"SC[%ld].AC.FsCtrl.SunYawRateDeadband = %18.12le\n",
            Isc,
            AC->FsCtrl.SunYawRateDeadband);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen],line,LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled) printf("%s",line);

         sprintf(line,"SC[%ld].AC.FsCtrl.SunYawError = %18.12le\n",
            Isc,
            AC->FsCtrl.SunYawError);
         LineLen = strlen(line);
         memcpy(&Msg[MsgLen],line,LineLen);
         MsgLen += LineLen;
         if (AC->EchoEnabled) printf("%s",line);

      }

      sprintf(line,"[EOF]\n\n");
      if (AC->EchoEnabled) printf("%s",line);

      LineLen = strlen(line);
      memcpy(&Msg[MsgLen],line,LineLen);
      MsgLen += LineLen;
      return (size_t) MsgLen;
}

