loop do
    cmd("EPS_MGR SET_MODE with CCSDS_STREAMID 6416, CCSDS_SEQUENCE 49152, CCSDS_LENGTH 2, CCSDS_FUNCCODE 4, CCSDS_CHECKSUM 0, MODE SAFE")
    wait_check("EPS_MGR FSW_TLM_PKT COMM_PAYLOAD_SWITCH == 'OFF'", 5)
    wait(1)
    wait_check("EPS_MGR FSW_TLM_PKT COMM_PAYLOAD_SWITCH == 'OFF'", 1)
    wait(2)
    cmd("EPS_MGR SET_MODE with CCSDS_STREAMID 6416, CCSDS_SEQUENCE 49152, CCSDS_LENGTH 2, CCSDS_FUNCCODE 4, CCSDS_CHECKSUM 0, MODE NOMINAL_OPS_PAYLOAD_ON")
    wait_check("EPS_MGR FSW_TLM_PKT COMM_PAYLOAD_SWITCH == 'ON'", 5)
    wait(1)
    wait_check("EPS_MGR FSW_TLM_PKT COMM_PAYLOAD_SWITCH == 'ON'", 1)
    wait(2)
end